### ISSUE TITLE
Why include mosquitto in Docker?

### ISSUE THREAD

**Issue by Diaoul** [owntracks/recorderd#13]
I wanted to run recorderd next to my Mosquitto instance but it seems they are both included in the docker image of recorderd.
Running multiple services in the same container is against Docker standards, the best way to run both is with a docker-compose configuration.

Can you provide a docker image without Mosquitto?

**Comment by jpmens** [comment]
Contributions accepted.

**Comment by xRmg** [comment]
I've created a docker setup without MQTT and without docker 
https://github.com/xRmg/owntracks-recorder @Diaoul this should get you in the right direction.

Regards,

**Comment by MyIgel** [comment]
I think you should create a pull request ;)

A nice feature could be to create two images, a base recorderd image (only the recorder) and an extended recorderd-mosquitto (buldled with mosquitto and its config) or etter an example docker compose file

**Comment by jpmens** [comment]
I will gladly repeat myself: we accept contributions and pull requests.

**Comment by MyIgel** [comment]
I think the base docker image should look like

```
FROM debian:stretch

ADD http://repo.owntracks.org/repo.owntracks.org.gpg.key /tmp/owntracks.gpg.key
RUN apt update &&\
    apt install -yqq gnupg && \
    apt-key add /tmp/owntracks.gpg.key && \
    rm /tmp/owntracks.gpg.key && \
    echo "deb  http://repo.owntracks.org/debian stretch main" > /etc/apt/sources.list.d/owntracks.list && \
    apt update && \
    apt install -yq ot-recorder && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8083

# For more options see https://github.com/owntracks/recorder#configuration-file
ENV OTR_HOST=mqtt
ENV OTR_PORT=1883

USER owntracks
CMD /usr/sbin/ot-recorder --http-host 0.0.0.0
```

**Comment by OmgImAlexis** [comment]
Here's a `docker-compose.yml` I whipped up today. Still a little rough though.

```
version: '3.4'

services:
    recorder:
        build: '.'
        networks:
            - default
        ports:
            - 11883:1883
            - 18883:8883
            - 8083:8083
        environment:
            - MQTTHOSTNAME: mqtt
            - IPLIST: '192.168.1.1 127.0.0.83 192.168.1.82'
            - HOSTLIST: 'foo.example.com bar.org.example.com ${cthostname}'
        deploy:
            replicas: 1
            restart_policy:
              condition: any

    mosquitto:
        image: eclipse-mosquitto
        networks:
            - default
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - mosquitto-data:/mosquitto/data/
            - mosquitto-logs:/mosquitto/mosquitto.log
        configs:
            - mosquitto-conf:/mosquitto/config/mosquitto.conf
        deploy:
            replicas: 1
            restart_policy:
              condition: any

volumes:
    - mosquitto-data:
    - mosquitto-logs:
configs:
    - mosquitto-conf:
```
